version: '3.7'
services:
  frontend:
    restart: always
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
